<a href="https://colab.research.google.com/github/fausharkgirl/GD_Terminal/blob/main/Whitehead_Assignment_week_2_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#Exercise 1
print ('Kimberly Whitehead')

Kimberly Whitehead


In [1]:
num1=4
num2=841
x = num1 + num2
print (x)

845


In [ ]:
n=6

In [2]:
seq = [1,2,3,4,5]
for item in seq:
    print(item)

1
2
3
4
5


In [ ]:
#Exercise 2
list = ['apple', 'orange', 'grape']
t = ('january', 'february', 'march', 'april')


In [3]:
thisdict = {
    "Canada": "38.25M",
    "Brazil": "214.3M",
    "United States": "331.9M"
}

In [4]:
#Excercise 3
import numpy as np

In [6]:
arr = np.arange (1,6)
arr

array([1, 2, 3, 4, 5])

In [7]:
np.mean (arr)

np.float64(3.0)

In [9]:
arr = np.random.randint(1,10,size=(2,3))
print (arr)

[[7 7 6]
 [7 6 5]]


In [11]:
arr.reshape(3,2)

array([[7, 7],
       [6, 7],
       [6, 5]])

In [12]:
#Exercise 4
arr1 = np.arange (1,4)
arr2 = np.arange (4,7)

In [13]:
arr1

array([1, 2, 3])

In [14]:
arr2

array([4, 5, 6])

In [15]:
np.concatenate((arr1, arr2))

array([1, 2, 3, 4, 5, 6])

In [16]:
p=arr1*arr2

In [17]:
p

array([ 4, 10, 18])

In [18]:
#Exercise 5

In [19]:
arr = np.array([10, 20, 30, 40, 50])
arr

array([10, 20, 30, 40, 50])

In [20]:
print (arr[3])

40


In [22]:
arr[1:4]

array([20, 30, 40])

In [23]:
#Exercise 6
M = np.random.randn(5,5)

In [24]:
M

array([[ 0.24127765,  1.27315815, -0.32080957, -0.98128989,  0.3605748 ],
       [ 1.12442842, -0.4233474 , -0.8385048 , -0.09409094, -0.28418833],
       [-1.94387158, -0.31100894,  1.17333196,  0.60392886, -0.00438813],
       [-2.24189306,  1.15030464, -0.01413164,  0.40662304,  0.35740558],
       [-1.12923016, -0.02480004, -2.1345837 , -1.12744804, -1.69402365]])

In [25]:
np.linalg.det(M)

np.float64(-0.6772890502578096)

In [26]:
#Exercise 7
A = np.array([[1, 2, 3],[4, 5, 6], [ 7, 8, 9]])
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [27]:
VB = np.array([[10],[11],[12]])
VB

array([[10],
       [11],
       [12]])

In [28]:
np.dot(A,VB)

array([[ 68],
       [167],
       [266]])

In [30]:
EV = np.linalg.eig(A)

In [31]:
EV

EigResult(eigenvalues=array([ 1.61168440e+01, -1.11684397e+00, -1.30367773e-15]), eigenvectors=array([[-0.23197069, -0.78583024,  0.40824829],
       [-0.52532209, -0.08675134, -0.81649658],
       [-0.8186735 ,  0.61232756,  0.40824829]]))

In [33]:
#Exercise 8
import scipy as sp

In [34]:
A = np.array([[2,1],[4,-3]])
v = np.array([[5],[2]])

In [35]:
A

array([[ 2,  1],
       [ 4, -3]])

In [36]:
v

array([[5],
       [2]])

In [37]:
result = sp.linalg.solve(A,v)

In [38]:
result

array([[1.7],
       [1.6]])

In [39]:
A = np.random.rand(100)

In [40]:
A

array([0.658808  , 0.63502902, 0.65745281, 0.40024719, 0.83248558,
       0.64063611, 0.89432891, 0.18619749, 0.8810903 , 0.31130191,
       0.26714018, 0.40540986, 0.27183051, 0.65440616, 0.46574668,
       0.52248425, 0.95739547, 0.9671761 , 0.75594574, 0.93482151,
       0.68670424, 0.2548566 , 0.29676733, 0.74707258, 0.47392061,
       0.84797782, 0.47697441, 0.40445456, 0.27382319, 0.90341019,
       0.3641758 , 0.44407526, 0.29666789, 0.02252995, 0.24803529,
       0.22302379, 0.83467775, 0.79497294, 0.24097455, 0.29403073,
       0.36774251, 0.21454215, 0.2698297 , 0.20810694, 0.65694939,
       0.66135434, 0.84083177, 0.93728409, 0.37001403, 0.08880104,
       0.84443342, 0.61964957, 0.35338599, 0.53397247, 0.66545327,
       0.10118335, 0.05124217, 0.22818734, 0.53719534, 0.5980395 ,
       0.4836233 , 0.89207723, 0.62188912, 0.96607381, 0.77049703,
       0.66483039, 0.76394565, 0.96133042, 0.07413484, 0.92347348,
       0.07614619, 0.708511  , 0.11078487, 0.23203796, 0.34124

In [42]:
np.mean(A)

np.float64(0.5284140680561343)

In [43]:
np.median(A)

np.float64(0.5257929493834661)